# [作業目標]
- 仿造範例的 One Hot Encoding, 將指定的資料進行編碼

# [作業重點]
- 將 sub_train 進行 One Hot Encoding 編碼 (In[4], Out[4])

In [1]:
import os
import numpy as np
import pandas as pd

In [7]:
# 設定 data_path, 並讀取 app_train
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

##./data/application_train.csv 
#代表程式會找的是跟 .ipython 相同目錄下 > data 資料夾 application_train.csv 檔案
# PS ./ 代表相同目錄、 ../ 代表上一層目錄

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [29]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [14]:
sub_train=pd.get_dummies(sub_train)
print(sub_train.shape)
sub_train.head()

(307511, 7)

,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0,0,0,0,0,0,0,1
1,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0

In [20]:
#補充labelencoding兩種方法(此處星期應該用onehot encoding比較好)
#1 sklearn
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le_count = 0

for col in sub_train:
    if len(sub_train[col])>2:
        #trian on training data
        le.fit(sub_train[col])
        #transform on training data
        sub_train[col]=le.transform(sub_train[col])
        
        le_count+=1
        
print('%d columns were label encoded' %le_count)
sub_train.head

7 columns were label encoded

<bound method NDFrame.head of         WEEKDAY_APPR_PROCESS_START_FRIDAY  WEEKDAY_APPR_PROCESS_START_MONDAY  \
0                                       0                                  0
1                                       0                                  1
2                                       0                                  1
3                                       0                                  0
4                                       0                                  0
5                                       0                                  0
6                                       0                                  0
7                                       0                                  1
8                                       0                                  0
9                                       0                                  0
10                                      0                                  0
11                                      1                                  0
12                                      1                                  0
13                                      0                                  0
14                                      0                                  1
15                                      0                                  0
16                                      0                                  0
17                                      0                                  1
18                                      1                                  0
19                                      0                                  1
20                                      1                                  0
21                                      0                                  1
22                                      0                                  0
23                                      1                                  0
24                                      0                                  0
25                                      0                                  0
26                                      0                                  1
27                                      0                                  0
28                                      0                                  0
29                                      0                                  0
...                                   ...                                ...
307481                                  1                                  0
307482                                  0                                  0
307483                                  0                                  1
307484                                  0                                  1
307485                                  0                                  0
307486                                  0                                  0
307487                                  0                                  0
307488                                  0                                  0
307489                                  1                                  0
307490                                  0                                  0
307491                                  0                                  0
307492                                  1                                  0
307493                                  0                                  1
307494                                  0                                  1
307495                                  0                                  0
307496                                  0                                  0
307497                                  0                                  0
307498                                  0                                  1
307499                                  0                                  0
307500                                  1                                  0
307501                                  0                                  0
307502                                  0                                  1
307503                                  0                                  0
307504                                  0                                  0
307505                                  0                                  1
307506                                  0                                  0
307507                                  0                                  1
307508                                  0                                  0
307509                                  0                                  0
307510                                  0                                  0

        WEEKDAY_APPR_PROCESS_START_SATURDAY  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
5                                         0
6                                         0
7                                         0
8                                         0
9                                         0
10                                        1
11                                        0
12                                        0
13                                        0
14                                        0
15                                        1
16                                        0
17                                        0
18                                        0
19                                        0
20                                        0
21                                        0
22                                        0
23                                        0
24                                        0
25                                        1
26                                        0
27                                        1
28                                        0
29                                        0
...                                     ...
307481                                    0
307482                                    0
307483                                    0
307484                                    0
307485                                    1
307486                                    1
307487                                    0
307488                                    0
307489                                    0
307490                                    1
307491                                    1
307492                                    0
307493                                    0
307494                                    0
307495                                    0
307496                                    0
307497                                    0
307498                                    0
307499                                    0
307500                                    0
307501                                    0
307502                                    0
307503                                    1
307504                                    0
307505                                    0
307506                                    0
307507                                    0
307508                                    0
307509                                    0
307510                                    0

        WEEKDAY_APPR_PROCESS_START_SUNDAY  \
0                                       0
1                                       0
2                                       0
3                                       0
4                                       0
5                                       0
6                                       1
7                                       0
8                                       0
9                                       0
10                                      0
11                                      0
12                                      0
13                                      0
14                                      0
15                                      0
16                                      0
17                                      0
18                                      0
19                                      0
20                                      0
21                                      0
22                                      0
23                                      0
24                                      0
25                                      0
26                                      0
27                                      0
28                                      0
29                                      0
...                                   ...
307481                                  0
307482                                  0
307483                                  0
307484                                  0
307485                                  0
307486                                  0
307487                                  0
307488                                  0
307489                                  0
307490                                  0
307491                                  0
307492                                  0
307493                                  0
307494                                  0
307495                                  0
307496                                  0
307497                                  0
307498                                  0
307499                                  0
307500                                  0
307501                                  0
307502                                  0
307503                                  0
307504                                  0
307505                                  0
307506                                  0
307507                                  0
307508                                  0
307509                                  0
307510                                  0

        WEEKDAY_APPR_PROCESS_START_THURSDAY  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         1
5                                         0
6                                         0
7                                         0
8                                         0
9                                         1
10                                        0
11                                        0
12                                        0
13                                        1
14                                        0
15                                        0
16                                        1
17                                        0
18                                        0
19                                        0
20                                        0
21                                        0
22                                        1
23                                        0
24                                        1
25                                        0
26                                        0
27                                        0
28                                        0
29                                        0
...                                     ...
307481                                    0
307482                                    1
307483                                    0
307484                                    0
307485                                    0
307486                                    0
307487                                    0
307488                                    0
307489                                    0
307490                                    0
307491                                    0
307492                                    0
307493                                    0
307494                                    0
307495                                    0
307496                                    1
307497                                    1
307498                                    0
307499                                    0
307500                                    0
307501                                    0
307502                                    0
307503                                    0
307504                                    0
307505                                    0
307506                                    1
307507                                    0
307508                                    1
307509                                    0
307510                                    1

        WEEKDAY_APPR_PROCESS_START_TUESDAY  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
5                                        0
6                                        0
7                                        0
8                                        0
9                                        0
10                                       0
11                                       0
12                                       0
13                                       0
14                                       0
15                                       0
16                                       0
17                                       0
18                                       0
19                                       0
20                                       0
21                                       0
22                                       0
23                                       0
24                                       0
25                                       0
26                                       0
27                                       0
28                                       0
29                                       1
...                                    ...
307481                                   0
307482                                   0
307483                                   0
307484                                   0
307485                                   0
307486                                   0
307487                                   0
307488                                   0
307489                                   0
307490                                   0
307491                                   0
307492                                   0
307493                                   0
307494                                   0
307495                                   0
307496                                   0
307497                                   0
307498                                   0
307499                                   1
307500                                   0
307501                                   0
307502                                   0
307503                                   0
307504                                   0
307505                                   0
307506                                   0
307507                                   0
307508                                   0
307509                                   0
307510                                   0

        WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0                                          1
1                                          0
2                                          0
3                                          1
4                                          0
5                                          1
6                                          0
7                                          0
8                                          1
9                                          0
10                                         0
11                                         0
12                                         0
13                                         0
14                                         0
15                                         0
16                                         0
17                                         0
18                                         0
19                                         0
20                                         0
21                                         0
22                                         0
23                                         0
24                                         0
25                                         0
26                                         0
27                                         0
28                                         1
29                                         0
...                                      ...
307481                                     0
307482                                     0
307483                                     0
307484                                     0
307485                                     0
307486                                     0
307487                                     1
307488                                     1
307489                                     0
307490                                     0
307491                                     0
307492                                     0
307493                                     0
307494                                     0
307495                                     1
307496                                     0
307497                                     0
307498                                     0
307499                                     0
307500                                     0
307501                                     1
307502                                     0
307503                                     0
307504                                     1
307505                                     0
307506                                     0
307507                                     0
307508                                     0
307509                                     1
307510                                     0

[307511 rows x 7 columns]>

In [30]:
#2 pandas
Mapp = {
    'WEDNESDAY':3,
    'MONDAY':1,
    'THURSDAY':4,
    'SUNDAY':7,
    'SATURDAY':6,
    'FRIDAY':5,
    'TUESDAY':2}
sub_train['WEEKDAY_APPR_PROCESS_START_LE']=sub_train['WEEKDAY_APPR_PROCESS_START'].map(Mapp)
sub_train.head()

  WEEKDAY_APPR_PROCESS_START  WEEKDAY_APPR_PROCESS_START_LE
0                  WEDNESDAY                              3
1                     MONDAY                              1
2                     MONDAY                              1
3                  WEDNESDAY                              3
4                   THURSDAY                              4